// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgELg-_p1ME4j2wwJg5oyNwkuwfykA9Do',
    appId: '1:335552836337:web:ad4243e87f8e7327ef2f50',
    messagingSenderId: '335552836337',
    projectId: 'mynotes-vickim2',
    authDomain: 'mynotes-vickim2.firebaseapp.com',
    storageBucket: 'mynotes-vickim2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8zo8OeHVSY-IrG_7dzjI4umQVo5ZRJDY',
    appId: '1:335552836337:android:80f0afcb1c0b320cef2f50',
    messagingSenderId: '335552836337',
    projectId: 'mynotes-vickim2',
    storageBucket: 'mynotes-vickim2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02Ok_oi0ZnikNWZfLt1-jaylbgNVFrFM',
    appId: '1:335552836337:ios:d0365413649d8049ef2f50',
    messagingSenderId: '335552836337',
    projectId: 'mynotes-vickim2',
    storageBucket: 'mynotes-vickim2.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC02Ok_oi0ZnikNWZfLt1-jaylbgNVFrFM',
    appId: '1:335552836337:ios:df0b6b6b47b81388ef2f50',
    messagingSenderId: '335552836337',
    projectId: 'mynotes-vickim2',
    storageBucket: 'mynotes-vickim2.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
